from typing import Protocol, Any, Optional


class ConfigProviderContract(Protocol):
    def __getattr__(self, item: str) -> Any: ...
    def get(self, key: str, default: Optional[Any] = None) -> Any: ...
    def save(self, data: dict): ...
