from typing import Protocol, List

import pandas as pd

from app.core.contracts.repository_contract import RepositoryContract


class MultiRepositoryContract(Protocol):
    def all(self) -> List[pd.DataFrame]: ...
    def combined(self) -> pd.DataFrame: ...
    def repositories(self) -> List[RepositoryContract]: ...
    def save(self, data: dict | pd.DataFrame) -> None: ...
